--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 15/02/2016 12:22:22
-- Server version: 5.6.14
-- Client version: 4.1
--
CREATE TABLE pdo.alunos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) DEFAULT NULL,
  nota INT(11) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 25
AVG_ROW_LENGTH = 682
CHARACTER SET utf8
COLLATE utf8_general_ci;
SET NAMES 'utf8';

INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(1, 'ALINE', 9, 'ALINE@ALINE.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(2, 'ALINE B', 7, 'ALINE@ALINE.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(3, 'ANDRE', 4, 'ANDRE@ANDRE.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(4, 'CLEUSA', 4, 'CLEUSA@CLEUSA.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(5, 'RODRIGO', 2, 'RODRIGO@RODRIGO.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(6, 'RAIANE', 4, 'RAIANE@RAIANE.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(7, 'FERNANDO', 6, 'FERNANDO@FERNANDO.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(8, 'JAMIE', 10, 'JAMIE@JAMIE.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(9, 'JEFFERSON', 10, 'JEFFERSON@JEFFERSON.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(10, 'OTAVIO', 6, 'OTAVIO@OTAVIO.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(11, 'TALITA', 8, 'TALITA@TALITA.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(12, 'MARIANGELA', 9, 'MARIANGELA@MARIANGELA.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(13, 'GABRIEL JORGE', 2, 'GABRIEL@GABRIEL.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(14, 'VAULENE', 7, 'VAULENE@VAULENE.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(15, 'JANETE', 9, 'JANETE@JANETE.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(16, 'JEFERSON', 4, 'JEFERSON@JEFERSON.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(17, 'THIAGO', 5, 'THIAGO@THIAGO.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(18, 'DOUGLAS', 8, 'DOUGLAS@DOUGLAS.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(19, 'LEONARDO', 9, 'LEONARDO@LEONARDO.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(20, 'BEATRIZ', 0, 'BEATRIZ@BEATRIZ.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(21, 'LUIZ', 8, 'LUIZ@LUIZ.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(22, 'TALITA', 6, 'TALITA@TALITA.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(23, 'GABRIEL', 7, 'GABRIEL@GABRIEL.com.br');
INSERT INTO pdo.alunos(id, nome, nota, email) VALUES
(24, 'CARLA', 5, 'CARLA@CARLA.com.br');